services:
  web-console:
    build:
      context: .
      dockerfile: docker/Dockerfile
    ports:
      - "${PORT:-3000}:3000"
    environment:
      - PORT=${PORT}
      - ADMIN_USER=${ADMIN_USER}
      - ADMIN_PASS=${ADMIN_PASS}
      - SESSION_SECRET=${SESSION_SECRET}
      - MC_CONTAINER=${MC_CONTAINER}
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
      - //var/run/docker.sock:/var/run/docker.sock
    restart: unless-stopped
